=== RamzesX/RestAssuredSpring/src/main/resources/History.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "get": {
      "type": "string"
    },
    "parameters": {
      "type": "object",
      "properties": {
        "country": {
          "type": "string"
        },
        "day": {
          "type": "string"
        }
      },
      "required": [
        "country"
      ]
    },
    "errors": {
      "type": "array",
      "items": {}
    },
    "results": {
      "type": "integer"
    },
    "response": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "continent": {
              "type": "string"
            },
            "country": {
              "type": "string"
            },
            "population": {
              "type": "integer"
            },
            "cases": {
              "type": "object",
              "properties": {
                "new": {
                  "type": "string"
                },
                "active": {
                  "type": "integer"
                },
                "critical": {
                  "type": "integer"
                },
                "recovered": {
                  "type": "integer"
                },
                "1M_pop": {
                  "type": "string"
                },
                "total": {
                  "type": "integer"
                }
              },
              "required": [
                "new",
                "active",
                "critical",
                "recovered",
                "1M_pop",
                "total"
              ]
            },
            "deaths": {
              "type": "object",
              "properties": {
                "new": {
                  "type": "string"
                },
                "1M_pop": {
                  "type": "string"
                },
                "total": {
                  "type": "integer"
                }
              },
              "required": [
                "new",
                "1M_pop",
                "total"
              ]
            },
            "tests": {
              "type": "object",
              "properties": {
                "1M_pop": {
                  "type": "string"
                },
                "total": {
                  "type": "integer"
                }
              },
              "required": [
                "1M_pop",
                "total"
              ]
            },
            "day": {
              "type": "string"
            },
            "time": {
              "type": "string"
            }
          },
          "required": [
            "continent",
            "country",
            "population",
            "cases",
            "deaths",
            "tests",
            "day",
            "time"
          ]
        }
      ]
    }
  },
  "required": [
    "get",
    "parameters",
    "errors",
    "results",
    "response"
  ]
}

=== RamzesX/RestAssuredSpring/src/main/resources/History.json
{
  "get": "history",
  "parameters": {
    "country": "usa",
    "day": "2020-06-02"
  },
  "errors": [

  ],
  "results": 48,
  "response": [
    {
      "continent": "North-America",
      "country": "USA",
      "population": 330843477,
      "cases": {
        "new": "+21829",
        "active": 1136777,
        "critical": 16947,
        "recovered": 615301,
        "1M_pop": "5619",
        "total": 1858999
      },
      "deaths": {
        "new": "+726",
        "1M_pop": "323",
        "total": 106921
      },
      "tests": {
        "1M_pop": "54856",
        "total": 18148683
      },
      "day": "2020-06-02",
      "time": "2020-06-02T00:00:05+00:00"
    }
  ]
}
